services:
  postgres:
    image: postgres:16
    container_name: univoyage_db_container
    environment:
      POSTGRES_DB: univoyage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d univoyage_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: univoyage_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/univoyage_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/univoyage_db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=admin

volumes:
  pgdata: