services:
  postgres:
    image: postgres:16
    container_name: univoyage_db_container
    environment:
      POSTGRES_DB: univoyage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust  # DODAJ OVO ZA TEST

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d univoyage_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: univoyage_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres         # Ime servisa iz docker-compose
      - DB_PORT=5432
      - DB_NAME=univoyage_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin

volumes:
  pgdata: