"""One-off: emit UPDATE statements for countries.currency_* — run once then delete if desired."""
m = {
    "AF": ("AFN", "Afghan afghani"),
    "AL": ("ALL", "Albanian lek"),
    "DZ": ("DZD", "Algerian dinar"),
    "AD": ("EUR", "Euro"),
    "AO": ("AOA", "Angolan kwanza"),
    "AG": ("XCD", "East Caribbean dollar"),
    "AR": ("ARS", "Argentine peso"),
    "AM": ("AMD", "Armenian dram"),
    "AU": ("AUD", "Australian dollar"),
    "AT": ("EUR", "Euro"),
    "AZ": ("AZN", "Azerbaijani manat"),
    "BS": ("BSD", "Bahamian dollar"),
    "BH": ("BHD", "Bahraini dinar"),
    "BD": ("BDT", "Bangladeshi taka"),
    "BB": ("BBD", "Barbadian dollar"),
    "BY": ("BYN", "Belarusian ruble"),
    "BE": ("EUR", "Euro"),
    "BZ": ("BZD", "Belize dollar"),
    "BJ": ("XOF", "West African CFA franc"),
    "BT": ("BTN", "Bhutanese ngultrum"),
    "BO": ("BOB", "Bolivian boliviano"),
    "BA": ("BAM", "Bosnia convertible mark"),
    "BW": ("BWP", "Botswana pula"),
    "BR": ("BRL", "Brazilian real"),
    "BN": ("BND", "Brunei dollar"),
    "BG": ("BGN", "Bulgarian lev"),
    "BF": ("XOF", "West African CFA franc"),
    "BI": ("BIF", "Burundian franc"),
    "CV": ("CVE", "Cape Verdean escudo"),
    "KH": ("KHR", "Cambodian riel"),
    "CM": ("XAF", "Central African CFA franc"),
    "CA": ("CAD", "Canadian dollar"),
    "CF": ("XAF", "Central African CFA franc"),
    "TD": ("XAF", "Central African CFA franc"),
    "CL": ("CLP", "Chilean peso"),
    "CN": ("CNY", "Chinese yuan"),
    "CO": ("COP", "Colombian peso"),
    "KM": ("KMF", "Comorian franc"),
    "CD": ("CDF", "Congolese franc"),
    "CG": ("XAF", "Central African CFA franc"),
    "CR": ("CRC", "Costa Rican colón"),
    "CI": ("XOF", "West African CFA franc"),
    "HR": ("EUR", "Euro"),
    "CU": ("CUP", "Cuban peso"),
    "CY": ("EUR", "Euro"),
    "CZ": ("CZK", "Czech koruna"),
    "DK": ("DKK", "Danish krone"),
    "DJ": ("DJF", "Djiboutian franc"),
    "DM": ("XCD", "East Caribbean dollar"),
    "DO": ("DOP", "Dominican peso"),
    "EC": ("USD", "US Dollar"),
    "EG": ("EGP", "Egyptian pound"),
    "SV": ("USD", "US Dollar"),
    "GQ": ("XAF", "Central African CFA franc"),
    "ER": ("ERN", "Eritrean nakfa"),
    "EE": ("EUR", "Euro"),
    "SZ": ("SZL", "Swazi lilangeni"),
    "ET": ("ETB", "Ethiopian birr"),
    "FJ": ("FJD", "Fijian dollar"),
    "FI": ("EUR", "Euro"),
    "FR": ("EUR", "Euro"),
    "GA": ("XAF", "Central African CFA franc"),
    "GM": ("GMD", "Gambian dalasi"),
    "GE": ("GEL", "Georgian lari"),
    "DE": ("EUR", "Euro"),
    "GH": ("GHS", "Ghanaian cedi"),
    "GR": ("EUR", "Euro"),
    "GD": ("XCD", "East Caribbean dollar"),
    "GT": ("GTQ", "Guatemalan quetzal"),
    "GN": ("GNF", "Guinean franc"),
    "GW": ("XOF", "West African CFA franc"),
    "GY": ("GYD", "Guyanese dollar"),
    "HT": ("HTG", "Haitian gourde"),
    "HN": ("HNL", "Honduran lempira"),
    "HU": ("HUF", "Hungarian forint"),
    "IS": ("ISK", "Icelandic króna"),
    "IN": ("INR", "Indian rupee"),
    "ID": ("IDR", "Indonesian rupiah"),
    "IR": ("IRR", "Iranian rial"),
    "IQ": ("IQD", "Iraqi dinar"),
    "IE": ("EUR", "Euro"),
    "IL": ("ILS", "Israeli new shekel"),
    "IT": ("EUR", "Euro"),
    "JM": ("JMD", "Jamaican dollar"),
    "JP": ("JPY", "Japanese yen"),
    "JO": ("JOD", "Jordanian dinar"),
    "KZ": ("KZT", "Kazakhstani tenge"),
    "KE": ("KES", "Kenyan shilling"),
    "KI": ("AUD", "Australian dollar"),
    "KP": ("KPW", "North Korean won"),
    "KR": ("KRW", "South Korean won"),
    "KW": ("KWD", "Kuwaiti dinar"),
    "KG": ("KGS", "Kyrgyzstani som"),
    "LA": ("LAK", "Lao kip"),
    "LV": ("EUR", "Euro"),
    "LB": ("LBP", "Lebanese pound"),
    "LS": ("LSL", "Lesotho loti"),
    "LR": ("LRD", "Liberian dollar"),
    "LY": ("LYD", "Libyan dinar"),
    "LI": ("CHF", "Swiss franc"),
    "LT": ("EUR", "Euro"),
    "LU": ("EUR", "Euro"),
    "MG": ("MGA", "Malagasy ariary"),
    "MW": ("MWK", "Malawian kwacha"),
    "MY": ("MYR", "Malaysian ringgit"),
    "MV": ("MVR", "Maldivian rufiyaa"),
    "ML": ("XOF", "West African CFA franc"),
    "MT": ("EUR", "Euro"),
    "MH": ("USD", "US Dollar"),
    "MR": ("MRU", "Mauritanian ouguiya"),
    "MU": ("MUR", "Mauritian rupee"),
    "MX": ("MXN", "Mexican peso"),
    "FM": ("USD", "US Dollar"),
    "MD": ("MDL", "Moldovan leu"),
    "MC": ("EUR", "Euro"),
    "MN": ("MNT", "Mongolian tögrög"),
    "ME": ("EUR", "Euro"),
    "MA": ("MAD", "Moroccan dirham"),
    "MZ": ("MZN", "Mozambican metical"),
    "MM": ("MMK", "Myanmar kyat"),
    "NA": ("NAD", "Namibian dollar"),
    "NR": ("AUD", "Australian dollar"),
    "NP": ("NPR", "Nepalese rupee"),
    "NL": ("EUR", "Euro"),
    "NZ": ("NZD", "New Zealand dollar"),
    "NI": ("NIO", "Nicaraguan córdoba"),
    "NE": ("XOF", "West African CFA franc"),
    "NG": ("NGN", "Nigerian naira"),
    "MK": ("MKD", "Macedonian denar"),
    "NO": ("NOK", "Norwegian krone"),
    "OM": ("OMR", "Omani rial"),
    "PK": ("PKR", "Pakistani rupee"),
    "PW": ("USD", "US Dollar"),
    "PS": ("ILS", "Israeli new shekel"),
    "PA": ("PAB", "Panamanian balboa"),
    "PG": ("PGK", "Papua New Guinean kina"),
    "PY": ("PYG", "Paraguayan guaraní"),
    "PE": ("PEN", "Peruvian sol"),
    "PH": ("PHP", "Philippine peso"),
    "PL": ("PLN", "Polish złoty"),
    "PT": ("EUR", "Euro"),
    "QA": ("QAR", "Qatari riyal"),
    "RO": ("RON", "Romanian leu"),
    "RU": ("RUB", "Russian ruble"),
    "RW": ("RWF", "Rwandan franc"),
    "KN": ("XCD", "East Caribbean dollar"),
    "LC": ("XCD", "East Caribbean dollar"),
    "VC": ("XCD", "East Caribbean dollar"),
    "WS": ("WST", "Samoan tālā"),
    "SM": ("EUR", "Euro"),
    "ST": ("STN", "São Tomé and Príncipe dobra"),
    "SA": ("SAR", "Saudi riyal"),
    "SN": ("XOF", "West African CFA franc"),
    "RS": ("RSD", "Serbian dinar"),
    "SC": ("SCR", "Seychellois rupee"),
    "SL": ("SLE", "Sierra Leonean leone"),
    "SG": ("SGD", "Singapore dollar"),
    "SK": ("EUR", "Euro"),
    "SI": ("EUR", "Euro"),
    "SB": ("SBD", "Solomon Islands dollar"),
    "SO": ("SOS", "Somali shilling"),
    "ZA": ("ZAR", "South African rand"),
    "SS": ("SSP", "South Sudanese pound"),
    "ES": ("EUR", "Euro"),
    "LK": ("LKR", "Sri Lankan rupee"),
    "SD": ("SDG", "Sudanese pound"),
    "SR": ("SRD", "Surinamese dollar"),
    "SE": ("SEK", "Swedish krona"),
    "CH": ("CHF", "Swiss franc"),
    "SY": ("SYP", "Syrian pound"),
    "TW": ("TWD", "New Taiwan dollar"),
    "TJ": ("TJS", "Tajikistani somoni"),
    "TZ": ("TZS", "Tanzanian shilling"),
    "TH": ("THB", "Thai baht"),
    "TL": ("USD", "US Dollar"),
    "TG": ("XOF", "West African CFA franc"),
    "TO": ("TOP", "Tongan paʻanga"),
    "TT": ("TTD", "Trinidad and Tobago dollar"),
    "TN": ("TND", "Tunisian dinar"),
    "TR": ("TRY", "Turkish lira"),
    "TM": ("TMT", "Turkmenistan manat"),
    "TV": ("AUD", "Australian dollar"),
    "UG": ("UGX", "Ugandan shilling"),
    "UA": ("UAH", "Ukrainian hryvnia"),
    "AE": ("AED", "UAE dirham"),
    "GB": ("GBP", "Pound sterling"),
    "US": ("USD", "US Dollar"),
    "UY": ("UYU", "Uruguayan peso"),
    "UZ": ("UZS", "Uzbekistani soʻm"),
    "VU": ("VUV", "Vanuatu vatu"),
    "VA": ("EUR", "Euro"),
    "VE": ("VES", "Venezuelan bolívar"),
    "VN": ("VND", "Vietnamese đồng"),
    "YE": ("YER", "Yemeni rial"),
    "ZM": ("ZMW", "Zambian kwacha"),
    "ZW": ("ZWL", "Zimbabwean dollar"),
}


def esc(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    for code in sorted(m):
        ccy, name = m[code]
        print(
            f"UPDATE countries SET currency_code = '{ccy}', currency_name = '{esc(name)}' WHERE iso_code = '{code}';"
        )


if __name__ == "__main__":
    main()
