-- We want to keep these dictionaries in separate tables to ensure data integrity and avoid duplication.
-- Table of all possible languages
CREATE TABLE languages (
    lang_code VARCHAR(2) PRIMARY KEY,
    lang_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE hobbies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hobby_name VARCHAR(50) UNIQUE NOT NULL
);
