-- Seed initial data into hobby, language, and country tables
-- This migration adds predefined hobbies, languages, and countries to the database because we use checker on registration
-- to validate user input against existing data, this way we ensure that the data is consistent and avoid user defining arbitrary values.
-- The ON CONFLICT DO NOTHING clause ensures that if the data already exists, it won't be duplicated.
-- User cannot modify these tables directly, so this seeding is a one-time operation during migration.
INSERT INTO hobbies (hobby_name) VALUES
('history'),
('hiking'),
('culture'),
('food'),
('photography'),
('adventure'),
('nightlife'),
('party'),
('nature'),
('beaches'),
('architecture'),
('museums'),
('shopping'),
('sports'),
('wildlife'),
('music'),
('art'),
('festivals')
ON CONFLICT (hobby_name) DO NOTHING;

INSERT INTO languages (lang_code, lang_name) VALUES
('en', 'English'),
('es', 'Spanish (Español)'),
('fr', 'French (Français)'),
('de', 'German (Deutsch)'),
('it', 'Italian (Italiano)'),
('pt', 'Portuguese (Português)'),
('zh', 'Chinese (中文)'),
('ja', 'Japanese (日本語)'),
('ko', 'Korean (한국어)'),
('ru', 'Russian (Русский)'),
('ar', 'Arabic (العربية)'),
('hi', 'Hindi (हिन्दी)'),
('nl', 'Dutch (Nederlands)'),
('sv', 'Swedish (Svenska)'),
('da', 'Danish (Dansk)'),
('no', 'Norwegian (Norsk)'),
('fi', 'Finnish (Suomi)'),
('pl', 'Polish (Polski)')
ON CONFLICT (lang_code) DO NOTHING;

INSERT INTO countries (iso_code, country_name) VALUES
('US', 'United States'),
('CA', 'Canada'),
('GB', 'United Kingdom'),
('AU', 'Australia'),
('NZ', 'New Zealand'),
('IE', 'Ireland'),
('FR', 'France'),
('DE', 'Germany'),
('IT', 'Italy'),
('ES', 'Spain'),
('PT', 'Portugal'),
('NL', 'Netherlands'),
('BE', 'Belgium'),
('CH', 'Switzerland'),
('AT', 'Austria'),
('SE', 'Sweden'),
('NO', 'Norway'),
('DK', 'Denmark'),
('FI', 'Finland'),
('IS', 'Iceland'),
('PL', 'Poland'),
('CZ', 'Czech Republic'),
('HU', 'Hungary'),
('RO', 'Romania'),
('GR', 'Greece'),
('TR', 'Turkey'),
('RU', 'Russia'),
('UA', 'Ukraine'),
('JP', 'Japan'),
('KR', 'South Korea'),
('CN', 'China'),
('TW', 'Taiwan'),
('HK', 'Hong Kong'),
('SG', 'Singapore'),
('MY', 'Malaysia'),
('TH', 'Thailand'),
('VN', 'Vietnam'),
('PH', 'Philippines'),
('ID', 'Indonesia'),
('IN', 'India'),
('PK', 'Pakistan'),
('BD', 'Bangladesh'),
('LK', 'Sri Lanka'),
('BT', 'Bhutan'),
('NP', 'Nepal'),
('MM', 'Myanmar'),
('KH', 'Cambodia'),
('LA', 'Laos'),
('MX', 'Mexico'),
('BR', 'Brazil'),
('AR', 'Argentina'),
('CL', 'Chile'),
('CO', 'Colombia'),
('PE', 'Peru'),
('VE', 'Venezuela'),
('EC', 'Ecuador'),
('BO', 'Bolivia'),
('PY', 'Paraguay'),
('UY', 'Uruguay'),
('CR', 'Costa Rica'),
('PA', 'Panama'),
('GT', 'Guatemala'),
('CU', 'Cuba'),
('DO', 'Dominican Republic'),
('JM', 'Jamaica'),
('TT', 'Trinidad and Tobago'),
('ZA', 'South Africa'),
('EG', 'Egypt'),
('MA', 'Morocco'),
('TN', 'Tunisia'),
('DZ', 'Algeria'),
('LY', 'Libya'),
('ET', 'Ethiopia'),
('KE', 'Kenya'),
('TZ', 'Tanzania'),
('UG', 'Uganda'),
('RW', 'Rwanda'),
('GH', 'Ghana'),
('NG', 'Nigeria'),
('SN', 'Senegal'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe'),
('BW', 'Botswana'),
('AE', 'United Arab Emirates'),
('SA', 'Saudi Arabia'),
('IL', 'Israel'),
('JO', 'Jordan'),
('LB', 'Lebanon'),
('SY', 'Syria'),
('IQ', 'Iraq'),
('IR', 'Iran'),
('AF', 'Afghanistan'),
('UZ', 'Uzbekistan'),
('KZ', 'Kazakhstan'),
('GE', 'Georgia'),
('AM', 'Armenia'),
('AZ', 'Azerbaijan')
ON CONFLICT (iso_code) DO NOTHING;