INSERT INTO languages(lang_code, lang_name) VALUES
    ('en', 'English'),
    ('es', 'Spanish (Español)'),
    ('fr', 'French (Français)'),
    ('de', 'German (Deutsch)'),
    ('it', 'Italian (Italiano)'),
    ('pt', 'Portuguese (Português)'),
    ('zh', 'Chinese (中文)'),
    ('ja', 'Japanese (日本語)'),
    ('ko', 'Korean (한국어)'),
    ('ru', 'Russian (Русский)'),
    ('ar', 'Arabic (العربية)'),
    ('hi', 'Hindi (हिन्दी)'),
    ('nl', 'Dutch (Nederlands)'),
    ('sv', 'Swedish (Svenska)'),
    ('da', 'Danish (Dansk)'),
    ('no', 'Norwegian (Norsk)'),
    ('fi', 'Finnish (Suomi)'),
    ('pl', 'Polish (Polski)'),
    ('bn', 'Bengali (বাংলা)'),
    ('mr', 'Marathi (मराठी)'),
    ('te', 'Telugu (తెలుగు)'),
    ('ta', 'Tamil (தமிழ்)'),
    ('vi', 'Vietnamese (Tiếng Việt)'),
    ('tr', 'Turkish (Türkçe)'),
    ('ur', 'Urdu (اردو)'),
    ('th', 'Thai (ไทย)'),
    ('gu', 'Gujarati (ગુજરાતી)'),
    ('uk', 'Ukrainian (Українська)'),
    ('kn', 'Kannada (ಕನ್ನಡ)'),
    ('ml', 'Malayalam (മലയാളം)'),
    ('ms', 'Malay (Bahasa Melayu)'),
    ('jv', 'Javanese (Basa Jawa)'),
    ('tl', 'Tagalog'),
    ('ro', 'Romanian (Română)'),
    ('el', 'Greek (Ελληνικά)'),
    ('hu', 'Hungarian (Magyar)'),
    ('cs', 'Czech (Čeština)'),
    ('bg', 'Bulgarian (Български)'),
    ('sr', 'Serbian (Српски)'),
    ('hr', 'Croatian (Hrvatski)'),
    ('sk', 'Slovak (Slovenčina)'),
    ('lt', 'Lithuanian (Lietuvių)'),
    ('lv', 'Latvian (Latviešu)'),
    ('et', 'Estonian (Eesti)'),
    ('si', 'Sinhala (සිංහල)'),
    ('ne', 'Nepali (नेपाली)'),
    ('my', 'Burmese (မြန်မာဘာသာ)'),
    ('am', 'Amharic (አማርኛ)'),
    ('id', 'Indonesian (Bahasa Indonesia)'),
    ('km', 'Khmer (ភាសាខ្មែរ)'),
    ('lo', 'Lao (ພາສາລາວ)'),
    ('ka', 'Georgian (ქართული)'),
    ('az', 'Azerbaijani (Azərbaycan dili)'),
    ('eu', 'Basque (Euskara)'),
    ('gl', 'Galician (Galego)'),
    ('is', 'Icelandic (Íslenska)'),
    ('ga', 'Irish (Gaeilge)'),
    ('cy', 'Welsh (Cymraeg)'),
    ('mt', 'Maltese (Malti)'),
    ('af', 'Afrikaans'),
    ('zu', 'Zulu (isiZulu)'),
    ('xh', 'Xhosa (isiXhosa)'),
    ('sw', 'Swahili (Kiswahili)'),
    ('ha', 'Hausa (Hausa)'),
    ('yo', 'Yoruba (Yorùbá)'),
    ('ig', 'Igbo (Igbo)'),
    ('so', 'Somali (Soomaali)'),
    ('or', 'Odia (ଓଡ଼ିଆ)'),
    ('as', 'Assamese (অসমীয়া)'),
    ('ks', 'Kashmiri (کٲشُر)'),
    ('sd', 'Sindhi (سنڌي)'),
    ('bo', 'Tibetan (བོད་སྐད་)'),
    ('dz', 'Dzongkha (རྫོང་ཁ་)'),
    ('mn', 'Mongolian (Монгол)'),
    ('kk', 'Kazakh (Қазақша)'),
    ('uz', 'Uzbek (Oʻzbekcha)'),
    ('tg', 'Tajik (Тоҷикӣ)'),
    ('tk', 'Turkmen (Türkmençe)'),
    ('ky', 'Kyrgyz (Кыргызча)'),
    ('tt', 'Tatar (Татарча)'),
    ('ba', 'Bashkir (Башҡорт теле)'),
    ('ce', 'Chechen (Нохчийн мотт)'),
    ('os', 'Ossetian (Ирон æвзаг)'),
    ('cv', 'Chuvash (Чӑваш чӗлхи)'),
    ('ud', 'Udmurt (Удмурт кыл)'),
    ('mi', 'Maori (Māori)'),
    ('sm', 'Samoan (Gagana Sāmoa)'),
    ('fj', 'Fijian (Vosa Vakaviti)'),
    ('to', 'Tongan (Lea Faka-Tonga)'),
    ('ty', 'Tahitian (Reo Tahiti)'),
    ('mg', 'Malagasy (Malagasy)'),
    ('ht', 'Haitian Creole (Kreyòl Ayisyen)'),
    ('lb', 'Luxembourgish (Lëtzebuergesch)'),
    ('sq', 'Albanian (Shqip)'),
    ('hy', 'Armenian (Հայերեն)'),
    ('mk', 'Macedonian (Македонски)'),
    ('sl', 'Slovenian (Slovenščina)'),
    ('bs', 'Bosnian (Bosanski)'),
    ('fa', 'Persian (Farsi)')
ON CONFLICT (lang_code) DO NOTHING;