INSERT INTO countries (iso_code, country_name, currency_code, currency_name) VALUES
('AF', 'Afghanistan', 'AFN', 'Afghan Afghani'),
('AL', 'Albania', 'ALL', 'Albanian Lek'),
('DZ', 'Algeria', 'DZD', 'Algerian Dinar'),
('AD', 'Andorra', 'EUR', 'Euro'),
('AO', 'Angola', 'AOA', 'Angolan Kwanza'),
('AG', 'Antigua and Barbuda', 'XCD', 'East Caribbean Dollar'),
('AR', 'Argentina', 'ARS', 'Argentine Peso'),
('AM', 'Armenia', 'AMD', 'Armenian Dram'),
('AU', 'Australia', 'AUD', 'Australian Dollar'),
('AT', 'Austria', 'EUR', 'Euro'),
('AZ', 'Azerbaijan', 'AZN', 'Azerbaijani Manat'),
('BS', 'Bahamas', 'BSD', 'Bahamian Dollar'),
('BH', 'Bahrain', 'BHD', 'Bahraini Dinar'),
('BD', 'Bangladesh', 'BDT', 'Bangladeshi Taka'),
('BB', 'Barbados', 'BBD', 'Barbadian Dollar'),
('BY', 'Belarus', 'BYN', 'Belarusian Ruble'),
('BE', 'Belgium', 'EUR', 'Euro'),
('BZ', 'Belize', 'BZD', 'Belize Dollar'),
('BJ', 'Benin', 'XOF', 'West African CFA Franc'),
('BT', 'Bhutan', 'BTN', 'Bhutanese Ngultrum'),
('BO', 'Bolivia', 'BOB', 'Bolivian Boliviano'),
('BA', 'Bosnia and Herzegovina', 'BAM', 'Bosnia and Herzegovina Convertible Mark'),
('BW', 'Botswana', 'BWP', 'Botswana Pula'),
('BR', 'Brazil', 'BRL', 'Brazilian Real'),
('BN', 'Brunei', 'BND', 'Brunei Dollar'),
('BG', 'Bulgaria', 'BGN', 'Bulgarian Lev'),
('BF', 'Burkina Faso', 'XOF', 'West African CFA Franc'),
('BI', 'Burundi', 'BIF', 'Burundian Franc'),
('CV', 'Cabo Verde', 'CVE', 'Cape Verdean Escudo'),
('KH', 'Cambodia', 'KHR', 'Cambodian Riel'),
('CM', 'Cameroon', 'XAF', 'Central African CFA Franc'),
('CA', 'Canada', 'CAD', 'Canadian Dollar'),
('CF', 'Central African Republic', 'XAF', 'Central African CFA Franc'),
('TD', 'Chad', 'XAF', 'Central African CFA Franc'),
('CL', 'Chile', 'CLP', 'Chilean Peso'),
('CN', 'China', 'CNY', 'Chinese Yuan'),
('CO', 'Colombia', 'COP', 'Colombian Peso'),
('KM', 'Comoros', 'KMF', 'Comorian Franc'),
('CD', 'Congo (DRC)', 'CDF', 'Congolese Franc'),
('CG', 'Congo (Republic)', 'XAF', 'Central African CFA Franc'),
('CR', 'Costa Rica', 'CRC', 'Costa Rican Colón'),
('CI', 'Côte d''Ivoire', 'XOF', 'West African CFA Franc'),
('HR', 'Croatia', 'EUR', 'Euro'),
('CU', 'Cuba', 'CUP', 'Cuban Peso'),
('CY', 'Cyprus', 'EUR', 'Euro'),
('CZ', 'Czech Republic', 'CZK', 'Czech Koruna'),
('DK', 'Denmark', 'DKK', 'Danish Krone'),
('DJ', 'Djibouti', 'DJF', 'Djiboutian Franc'),
('DM', 'Dominica', 'XCD', 'East Caribbean Dollar'),
('DO', 'Dominican Republic', 'DOP', 'Dominican Peso'),
('EC', 'Ecuador', 'USD', 'US Dollar'),
('EG', 'Egypt', 'EGP', 'Egyptian Pound'),
('SV', 'El Salvador', 'USD', 'US Dollar'),
('GQ', 'Equatorial Guinea', 'XAF', 'Central African CFA Franc'),
('ER', 'Eritrea', 'ERN', 'Eritrean Nakfa'),
('EE', 'Estonia', 'EUR', 'Euro'),
('SZ', 'Eswatini', 'SZL', 'Swazi Lilangeni'),
('ET', 'Ethiopia', 'ETB', 'Ethiopian Birr'),
('FJ', 'Fiji', 'FJD', 'Fijian Dollar'),
('FI', 'Finland', 'EUR', 'Euro'),
('FR', 'France', 'EUR', 'Euro'),
('GA', 'Gabon', 'XAF', 'Central African CFA Franc'),
('GM', 'Gambia', 'GMD', 'Gambian Dalasi'),
('GE', 'Georgia', 'GEL', 'Georgian Lari'),
('DE', 'Germany', 'EUR', 'Euro'),
('GH', 'Ghana', 'GHS', 'Ghanaian Cedi'),
('GR', 'Greece', 'EUR', 'Euro'),
('GD', 'Grenada', 'XCD', 'East Caribbean Dollar'),
('GT', 'Guatemala', 'GTQ', 'Guatemalan Quetzal'),
('GN', 'Guinea', 'GNF', 'Guinean Franc'),
('GW', 'Guinea-Bissau', 'XOF', 'West African CFA Franc'),
('GY', 'Guyana', 'GYD', 'Guyanese Dollar'),
('HK', 'Hong Kong', 'HKD', 'Hong Kong Dollar'),
('HT', 'Haiti', 'HTG', 'Haitian Gourde'),
('HN', 'Honduras', 'HNL', 'Honduran Lempira'),
('HU', 'Hungary', 'HUF', 'Hungarian Forint'),
('IS', 'Iceland', 'ISK', 'Icelandic Króna'),
('IN', 'India', 'INR', 'Indian Rupee'),
('ID', 'Indonesia', 'IDR', 'Indonesian Rupiah'),
('IR', 'Iran', 'IRR', 'Iranian Rial'),
('IQ', 'Iraq', 'IQD', 'Iraqi Dinar'),
('IE', 'Ireland', 'EUR', 'Euro'),
('IL', 'Israel', 'ILS', 'Israeli New Shekel'),
('IT', 'Italy', 'EUR', 'Euro'),
('JM', 'Jamaica', 'JMD', 'Jamaican Dollar'),
('JP', 'Japan', 'JPY', 'Japanese Yen'),
('JO', 'Jordan', 'JOD', 'Jordanian Dinar'),
('KZ', 'Kazakhstan', 'KZT', 'Kazakhstani Tenge'),
('KE', 'Kenya', 'KES', 'Kenyan Shilling'),
('KI', 'Kiribati', 'AUD', 'Australian Dollar'),
('KP', 'North Korea', 'KPW', 'North Korean Won'),
('KR', 'South Korea', 'KRW', 'South Korean Won'),
('KW', 'Kuwait', 'KWD', 'Kuwaiti Dinar'),
('KG', 'Kyrgyzstan', 'KGS', 'Kyrgyzstani Som'),
('LA', 'Laos', 'LAK', 'Lao Kip'),
('LV', 'Latvia', 'EUR', 'Euro'),
('LB', 'Lebanon', 'LBP', 'Lebanese Pound'),
('LS', 'Lesotho', 'LSL', 'Lesotho Loti'),
('LR', 'Liberia', 'LRD', 'Liberian Dollar'),
('LY', 'Libya', 'LYD', 'Libyan Dinar'),
('LI', 'Liechtenstein', 'CHF', 'Swiss Franc'),
('LT', 'Lithuania', 'EUR', 'Euro'),
('LU', 'Luxembourg', 'EUR', 'Euro'),
('MG', 'Madagascar', 'MGA', 'Malagasy Ariary'),
('MW', 'Malawi', 'MWK', 'Malawian Kwacha'),
('MY', 'Malaysia', 'MYR', 'Malaysian Ringgit'),
('MV', 'Maldives', 'MVR', 'Maldivian Rufiyaa'),
('ML', 'Mali', 'XOF', 'West African CFA Franc'),
('MT', 'Malta', 'EUR', 'Euro'),
('MH', 'Marshall Islands', 'USD', 'US Dollar'),
('MR', 'Mauritania', 'MRU', 'Mauritanian Ouguiya'),
('MU', 'Mauritius', 'MUR', 'Mauritian Rupee'),
('MX', 'Mexico', 'MXN', 'Mexican Peso'),
('FM', 'Micronesia', 'USD', 'US Dollar'),
('MD', 'Moldova', 'MDL', 'Moldovan Leu'),
('MC', 'Monaco', 'EUR', 'Euro'),
('MN', 'Mongolia', 'MNT', 'Mongolian Tögrög'),
('ME', 'Montenegro', 'EUR', 'Euro'),
('MA', 'Morocco', 'MAD', 'Moroccan Dirham'),
('MZ', 'Mozambique', 'MZN', 'Mozambican Metical'),
('MM', 'Myanmar', 'MMK', 'Myanmar Kyat'),
('NA', 'Namibia', 'NAD', 'Namibian Dollar'),
('NR', 'Nauru', 'AUD', 'Australian Dollar'),
('NP', 'Nepal', 'NPR', 'Nepalese Rupee'),
('NL', 'Netherlands', 'EUR', 'Euro'),
('NZ', 'New Zealand', 'NZD', 'New Zealand Dollar'),
('NI', 'Nicaragua', 'NIO', 'Nicaraguan Córdoba'),
('NE', 'Niger', 'XOF', 'West African CFA Franc'),
('NG', 'Nigeria', 'NGN', 'Nigerian Naira'),
('MK', 'North Macedonia', 'MKD', 'Macedonian Denar'),
('NO', 'Norway', 'NOK', 'Norwegian Krone'),
('OM', 'Oman', 'OMR', 'Omani Rial'),
('PK', 'Pakistan', 'PKR', 'Pakistani Rupee'),
('PW', 'Palau', 'USD', 'US Dollar'),
('PS', 'Palestine', 'ILS', 'Israeli New Shekel'),
('PA', 'Panama', 'PAB', 'Panamanian Balboa'),
('PG', 'Papua New Guinea', 'PGK', 'Papua New Guinean Kina'),
('PY', 'Paraguay', 'PYG', 'Paraguayan Guaraní'),
('PE', 'Peru', 'PEN', 'Peruvian Sol'),
('PH', 'Philippines', 'PHP', 'Philippine Peso'),
('PL', 'Poland', 'PLN', 'Polish Złoty'),
('PT', 'Portugal', 'EUR', 'Euro'),
('PR', 'Puerto Rico', 'USD', 'US Dollar'),
('QA', 'Qatar', 'QAR', 'Qatari Riyal'),
('RO', 'Romania', 'RON', 'Romanian Leu'),
('RU', 'Russia', 'RUB', 'Russian Ruble'),
('RW', 'Rwanda', 'RWF', 'Rwandan Franc'),
('KN', 'Saint Kitts and Nevis', 'XCD', 'East Caribbean Dollar'),
('LC', 'Saint Lucia', 'XCD', 'East Caribbean Dollar'),
('VC', 'Saint Vincent and the Grenadines', 'XCD', 'East Caribbean Dollar'),
('WS', 'Samoa', 'WST', 'Samoan Tala'),
('SM', 'San Marino', 'EUR', 'Euro'),
('ST', 'Sao Tome and Principe', 'STN', 'São Tomé and Príncipe Dobra'),
('SA', 'Saudi Arabia', 'SAR', 'Saudi Riyal'),
('SN', 'Senegal', 'XOF', 'West African CFA Franc'),
('RS', 'Serbia', 'RSD', 'Serbian Dinar'),
('SC', 'Seychelles', 'SCR', 'Seychellois Rupee'),
('SL', 'Sierra Leone', 'SLE', 'Sierra Leonean Leone'),
('SG', 'Singapore', 'SGD', 'Singapore Dollar'),
('SK', 'Slovakia', 'EUR', 'Euro'),
('SI', 'Slovenia', 'EUR', 'Euro'),
('SB', 'Solomon Islands', 'SBD', 'Solomon Islands Dollar'),
('SO', 'Somalia', 'SOS', 'Somali Shilling'),
('ZA', 'South Africa', 'ZAR', 'South African Rand'),
('SS', 'South Sudan', 'SSP', 'South Sudanese Pound'),
('ES', 'Spain', 'EUR', 'Euro'),
('LK', 'Sri Lanka', 'LKR', 'Sri Lankan Rupee'),
('SD', 'Sudan', 'SDG', 'Sudanese Pound'),
('SR', 'Suriname', 'SRD', 'Surinamese Dollar'),
('SE', 'Sweden', 'SEK', 'Swedish Krona'),
('CH', 'Switzerland', 'CHF', 'Swiss Franc'),
('SY', 'Syria', 'SYP', 'Syrian Pound'),
('TW', 'Taiwan', 'TWD', 'New Taiwan Dollar'),
('TJ', 'Tajikistan', 'TJS', 'Tajikistani Somoni'),
('TZ', 'Tanzania', 'TZS', 'Tanzanian Shilling'),
('TH', 'Thailand', 'THB', 'Thai Baht'),
('TL', 'Timor-Leste', 'USD', 'US Dollar'),
('TG', 'Togo', 'XOF', 'West African CFA Franc'),
('TO', 'Tonga', 'TOP', 'Tongan Paʻanga'),
('TT', 'Trinidad and Tobago', 'TTD', 'Trinidad and Tobago Dollar'),
('TN', 'Tunisia', 'TND', 'Tunisian Dinar'),
('TR', 'Turkey', 'TRY', 'Turkish Lira'),
('TM', 'Turkmenistan', 'TMT', 'Turkmenistani Manat'),
('TV', 'Tuvalu', 'AUD', 'Australian Dollar'),
('UG', 'Uganda', 'UGX', 'Ugandan Shilling'),
('UA', 'Ukraine', 'UAH', 'Ukrainian Hryvnia'),
('AE', 'United Arab Emirates', 'AED', 'UAE Dirham'),
('GB', 'United Kingdom', 'GBP', 'Pound Sterling'),
('US', 'United States', 'USD', 'US Dollar'),
('UY', 'Uruguay', 'UYU', 'Uruguayan Peso'),
('UZ', 'Uzbekistan', 'UZS', 'Uzbekistani Soʻm'),
('VU', 'Vanuatu', 'VUV', 'Vanuatu Vatu'),
('VA', 'Vatican City', 'EUR', 'Euro'),
('VE', 'Venezuela', 'VES', 'Venezuelan Bolívar'),
('VN', 'Vietnam', 'VND', 'Vietnamese Đồng'),
('YE', 'Yemen', 'YER', 'Yemeni Rial'),
('ZM', 'Zambia', 'ZMW', 'Zambian Kwacha'),
('ZW', 'Zimbabwe', 'ZWG', 'Zimbabwe Gold')
ON CONFLICT (iso_code) DO NOTHING;
