databaseType = "PostgreSql"
id = "c293e92a-7944-46cc-9732-a6508b20f711"
name = "UniVoyage"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:postgresql://127.0.0.1:5433/univoyage"
schemas = [ "public" ]
