// Validation constants
export const VALIDATION = {
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  MIN_PASSWORD_LENGTH: 3,
} as const;

// Interests/Hobbies options
export const TRAVEL_INTERESTS = [
  { value: "1", label: "🏛️ History" },
  { value: "2", label: "⛰️ Hiking" },
  { value: "3", label: "🎭 Culture" },
  { value: "4", label: "🍕 Food & Dining" },
  { value: "5", label: "📸 Photography" },
  { value: "6", label: "🏔️ Adventure" },
  { value: "7", label: "🍻 Nightlife" },
  { value: "8", label: "🎉 Party" },
  { value: "9", label: "🌲 Nature" },
  { value: "10", label: "🏖️ Beaches" },
  { value: "11", label: "🏛️ Architecture" },
  { value: "12", label: "🖼️ Museums" },
  { value: "13", label: "🛍️ Shopping" },
  { value: "14", label: "⚽ Sports" },
  { value: "15", label: "🦁 Wildlife" },
  { value: "16", label: "🎵 Music" },
  { value: "17", label: "🎨 Art" },
  { value: "18", label: "🎪 Festivals" },
];

// Languages options
export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish (Español)" },
  { value: "fr", label: "French (Français)" },
  { value: "de", label: "German (Deutsch)" },
  { value: "it", label: "Italian (Italiano)" },
  { value: "pt", label: "Portuguese (Português)" },
  { value: "zh", label: "Chinese (中文)" },
  { value: "ja", label: "Japanese (日本語)" },
  { value: "ko", label: "Korean (한국어)" },
  { value: "ru", label: "Russian (Русский)" },
  { value: "ar", label: "Arabic (العربية)" },
  { value: "hi", label: "Hindi (हिन्दी)" },
  { value: "nl", label: "Dutch (Nederlands)" },
  { value: "sv", label: "Swedish (Svenska)" },
  { value: "da", label: "Danish (Dansk)" },
  { value: "no", label: "Norwegian (Norsk)" },
  { value: "fi", label: "Finnish (Suomi)" },
  { value: "pl", label: "Polish (Polski)" },
];

// Countries options
export const COUNTRIES = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "IE", label: "Ireland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "PT", label: "Portugal" },
  { value: "NL", label: "Netherlands" },
  { value: "BE", label: "Belgium" },
  { value: "CH", label: "Switzerland" },
  { value: "AT", label: "Austria" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "IS", label: "Iceland" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "RO", label: "Romania" },
  { value: "GR", label: "Greece" },
  { value: "TR", label: "Turkey" },
  { value: "RU", label: "Russia" },
  { value: "UA", label: "Ukraine" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CN", label: "China" },
  { value: "TW", label: "Taiwan" },
  { value: "HK", label: "Hong Kong" },
  { value: "SG", label: "Singapore" },
  { value: "MY", label: "Malaysia" },
  { value: "TH", label: "Thailand" },
  { value: "VN", label: "Vietnam" },
  { value: "PH", label: "Philippines" },
  { value: "ID", label: "Indonesia" },
  { value: "IN", label: "India" },
  { value: "PK", label: "Pakistan" },
  { value: "BD", label: "Bangladesh" },
  { value: "LK", label: "Sri Lanka" },
  { value: "BT", label: "Bhutan" },
  { value: "NP", label: "Nepal" },
  { value: "MM", label: "Myanmar" },
  { value: "KH", label: "Cambodia" },
  { value: "LA", label: "Laos" },
  { value: "MX", label: "Mexico" },
  { value: "BR", label: "Brazil" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "PE", label: "Peru" },
  { value: "VE", label: "Venezuela" },
  { value: "EC", label: "Ecuador" },
  { value: "BO", label: "Bolivia" },
  { value: "PY", label: "Paraguay" },
  { value: "UY", label: "Uruguay" },
  { value: "CR", label: "Costa Rica" },
  { value: "PA", label: "Panama" },
  { value: "GT", label: "Guatemala" },
  { value: "CU", label: "Cuba" },
  { value: "DO", label: "Dominican Republic" },
  { value: "JM", label: "Jamaica" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "ZA", label: "South Africa" },
  { value: "EG", label: "Egypt" },
  { value: "MA", label: "Morocco" },
  { value: "TN", label: "Tunisia" },
  { value: "DZ", label: "Algeria" },
  { value: "LY", label: "Libya" },
  { value: "ET", label: "Ethiopia" },
  { value: "KE", label: "Kenya" },
  { value: "TZ", label: "Tanzania" },
  { value: "UG", label: "Uganda" },
  { value: "RW", label: "Rwanda" },
  { value: "GH", label: "Ghana" },
  { value: "NG", label: "Nigeria" },
  { value: "SN", label: "Senegal" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "BW", label: "Botswana" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "IL", label: "Israel" },
  { value: "JO", label: "Jordan" },
  { value: "LB", label: "Lebanon" },
  { value: "SY", label: "Syria" },
  { value: "IQ", label: "Iraq" },
  { value: "IR", label: "Iran" },
  { value: "AF", label: "Afghanistan" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "GE", label: "Georgia" },
  { value: "AM", label: "Armenia" },
  { value: "AZ", label: "Azerbaijan" },
];

// API constants
export const API_CONSTANTS = {
  AUTH_TOKEN_KEY: 'auth_token',
  USER_KEY: 'user',
  DEFAULT_TIMEOUT: 10000,
} as const;

// UI constants
export const UI_CONSTANTS = {
  PROFILE_PICTURE_SIZE: {
    SMALL: 24, // Header profile picture
    LARGE: 80, // Profile page picture
  },
  TOAST_DURATION: 4000,
} as const;
