// Validation constants
export const VALIDATION = {
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  MIN_PASSWORD_LENGTH: 3,
} as const;

// Interests/Hobbies options
export const TRAVEL_INTERESTS = [
  { value: "1", label: "🏛️ History" },
  { value: "2", label: "⛰️ Hiking" },
  { value: "3", label: "🎭 Culture" },
  { value: "4", label: "🍕 Food & Dining" },
  { value: "5", label: "📸 Photography" },
  { value: "6", label: "🏔️ Adventure" },
  { value: "7", label: "🍻 Nightlife" },
  { value: "8", label: "🎉 Party" },
  { value: "9", label: "🌲 Nature" },
  { value: "10", label: "🏖️ Beaches" },
  { value: "11", label: "🏛️ Architecture" },
  { value: "12", label: "🖼️ Museums" },
  { value: "13", label: "🛍️ Shopping" },
  { value: "14", label: "⚽ Sports" },
  { value: "15", label: "🦁 Wildlife" },
  { value: "16", label: "🎵 Music" },
  { value: "17", label: "🎨 Art" },
  { value: "18", label: "🎪 Festivals" },
  { value: "19", label: "🧖‍♀️ Wellness & Spa" },
  { value: "20", label: "🍷 Wine & Tasting" },
  { value: "21", label: "🤝 Volunteering" },
  { value: "22", label: "🚗 Road Trips" },
  { value: "23", label: "⛵ Sailing & Boating" },
  { value: "24", label: "🧘‍♀️ Relaxation & Meditation" },
  { value: "25", label: "🌌 Stargazing" },
  { value: "26", label: "📜 Genealogy & Ancestry" },
  { value: "27", label: "🥕 Local Markets" },
  { value: "28", label: "📚 Reading & Writing" },
  { value: "29", label: "🐠 Scuba Diving & Snorkeling" },
  { value: "30", label: "⛳ Golf & Country Clubs" },
];

// Languages options
export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish (Español)" },
  { value: "fr", label: "French (Français)" },
  { value: "de", label: "German (Deutsch)" },
  { value: "it", label: "Italian (Italiano)" },
  { value: "pt", label: "Portuguese (Português)" },
  { value: "zh", label: "Chinese (中文)" },
  { value: "ja", label: "Japanese (日本語)" },
  { value: "ko", label: "Korean (한국어)" },
  { value: "ru", label: "Russian (Русский)" },
  { value: "ar", label: "Arabic (العربية)" },
  { value: "hi", label: "Hindi (हिन्दी)" },
  { value: "nl", label: "Dutch (Nederlands)" },
  { value: "sv", label: "Swedish (Svenska)" },
  { value: "da", label: "Danish (Dansk)" },
  { value: "no", label: "Norwegian (Norsk)" },
  { value: "fi", label: "Finnish (Suomi)" },
  { value: "pl", label: "Polish (Polski)" },
  { value: "bn", label: "Bengali (বাংলা)" },
  { value: "mr", label: "Marathi (मराठी)" },
  { value: "te", label: "Telugu (తెలుగు)" },
  { value: "ta", label: "Tamil (தமிழ்)" },
  { value: "vi", label: "Vietnamese (Tiếng Việt)" },
  { value: "tr", label: "Turkish (Türkçe)" },
  { value: "ur", label: "Urdu (اردو)" },
  { value: "th", label: "Thai (ไทย)" },
  { value: "gu", label: "Gujarati (ગુજરાતી)" },
  { value: "uk", label: "Ukrainian (Українська)" },
  { value: "kn", label: "Kannada (ಕನ್ನಡ)" },
  { value: "ml", label: "Malayalam (മലയാളം)" },
  { value: "ms", label: "Malay (Bahasa Melayu)" },
  { value: "jv", label: "Javanese (Basa Jawa)" },
  { value: "tl", label: "Tagalog" },
  { value: "ro", label: "Romanian (Română)" },
  { value: "el", label: "Greek (Ελληνικά)" },
  { value: "hu", label: "Hungarian (Magyar)" },
  { value: "cs", label: "Czech (Čeština)" },
  { value: "bg", label: "Bulgarian (Български)" },
  { value: "sr", label: "Serbian (Српски)" },
  { value: "hr", label: "Croatian (Hrvatski)" },
  { value: "sk", label: "Slovak (Slovenčina)" },
  { value: "lt", label: "Lithuanian (Lietuvių)" },
  { value: "lv", label: "Latvian (Latviešu)" },
  { value: "et", label: "Estonian (Eesti)" },
  { value: "si", label: "Sinhala (සිංහල)" },
  { value: "ne", label: "Nepali (नेपाली)" },
  { value: "my", label: "Burmese (မြန်မာဘာသာ)" },
  { value: "am", label: "Amharic (አማርኛ)" },
  { value: "id", label: "Indonesian (Bahasa Indonesia)" },
  { value: "km", label: "Khmer (ភាសាខ្មែរ)" },
  { value: "lo", label: "Lao (ພາສາລາວ)" },
  { value: "ka", label: "Georgian (ქართული)" },
  { value: "az", label: "Azerbaijani (Azərbaycan dili)" },
  { value: "eu", label: "Basque (Euskara)" },
  { value: "gl", label: "Galician (Galego)" },
  { value: "is", label: "Icelandic (Íslenska)" },
  { value: "ga", label: "Irish (Gaeilge)" },
  { value: "cy", label: "Welsh (Cymraeg)" },
  { value: "mt", label: "Maltese (Malti)" },
  { value: "af", label: "Afrikaans" },
  { value: "zu", label: "Zulu (isiZulu)" },
  { value: "xh", label: "Xhosa (isiXhosa)" },
  { value: "sw", label: "Swahili (Kiswahili)" },
  { value: "ha", label: "Hausa (Hausa)" },
  { value: "yo", label: "Yoruba (Yorùbá)" },
  { value: "ig", label: "Igbo (Igbo)" },
  { value: "so", label: "Somali (Soomaali)" },
  { value: "or", label: "Odia (ଓଡ଼ିଆ)" },
  { value: "as", label: "Assamese (অসমীয়া)" },
  { value: "ks", label: "Kashmiri (کٲشُر)" },
  { value: "sd", label: "Sindhi (سنڌي)" },
  { value: "bo", label: "Tibetan (བོད་སྐད་)" },
  { value: "dz", label: "Dzongkha (རྫོང་ཁ་)" },
  { value: "mn", label: "Mongolian (Монгол)" },
  { value: "kk", label: "Kazakh (Қазақша)" },
  { value: "uz", label: "Uzbek (Oʻzbekcha)" },
  { value: "tg", label: "Tajik (Тоҷикӣ)" },
  { value: "tk", label: "Turkmen (Türkmençe)" },
  { value: "ky", label: "Kyrgyz (Кыргызча)" },
  { value: "tt", label: "Tatar (Татарча)" },
  { value: "ba", label: "Bashkir (Башҡорт теле)" },
  { value: "ce", label: "Chechen (Нохчийн мотт)" },
  { value: "os", label: "Ossetian (Ирон æвзаг)" },
  { value: "cv", label: "Chuvash (Чӑваш чӗлхи)" },
  { value: "ud", label: "Udmurt (Удмурт кыл)" },
  { value: "mi", label: "Maori (Māori)" },
  { value: "sm", label: "Samoan (Gagana Sāmoa)" },
  { value: "fj", label: "Fijian (Vosa Vakaviti)" },
  { value: "to", label: "Tongan (Lea Faka-Tonga)" },
  { value: "ty", label: "Tahitian (Reo Tahiti)" },
  { value: "mg", label: "Malagasy (Malagasy)" },
  { value: "ht", label: "Haitian Creole (Kreyòl Ayisyen)" },
  { value: "lb", label: "Luxembourgish (Lëtzebuergesch)" },
  { value: "sq", label: "Albanian (Shqip)" },
  { value: "hy", label: "Armenian (Հայերեն)" },
  { value: "mk", label: "Macedonian (Македонски)" },
  { value: "sl", label: "Slovenian (Slovenščina)" },
  { value: "bs", label: "Bosnian (Bosanski)" },
  { value: "fa", label: "Persian (Farsi)" },
];

// Countries options
export const COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CD", label: "Congo (DRC)" },
  { value: "CG", label: "Congo (Republic)" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "North Korea" },
  { value: "KR", label: "South Korea" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

// API constants
export const API_CONSTANTS = {
  AUTH_TOKEN_KEY: 'auth_token',
  USER_KEY: 'user',
  CSRF_COOKIE_NAME: 'csrf_token',
  DEFAULT_TIMEOUT: 10000,
} as const;

